// react/example/app.js
import React from 'react'
import MaskedInput from '../src/reactTextMask'

export default () => (
  <form className='form-horizontal'>
    <div className='form-group'>
      <label htmlFor='1' className='col-sm-2 control-label'>Masked input</label>

      <div className='col-sm-10'>
        <MaskedInput
          mask={[
            '(',
            /[1-9]/,
            /\d/,
            /\d/,
            ')',
            ' ',
            /\d/,
            /\d/,
            /\d/,
            '-',
            /\d/,
            /\d/,
            /\d/,
            /\d/,
          ]}
          className='form-control'
          id='1'
          type='text'
        />
      </div>
    </div>
  </form>
)

// vue/example/app.vue
<template>
  <form class="form-horizontal">
    <div class="form-group">
      <label for="1" class="col-sm-4 control-label">Masked input</label>

      <div class="col-sm-8">
        <input
          id="1"
          type="text"
          name="phone"
          class="form-control"
          v-model="phone"
          v-text-mask="maskOptions">
      </div>
    </div>

    <div class="form-group">
      <label for="2" class="col-sm-4 control-label">Model</label>

      <div class="col-sm-8">
        <pre>{{ phone }}</pre>
      </div>
    </div>
  </form>
</template>

<script>
export default {
  data () {
    return {
      phone: '',

      maskOptions: {
        mask: ['(', /[1-9]/, /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/]
      }
    }
  }
}
</script>
